### ISSUE TITLE
Spam/Scam detection in image caption (also forwarded)

### ISSUE THREAD

**Issue by mik3sw** [mik3sw/GoogleAssistantBot#8]
A new spam type is sending images with scam products and in caption links and spam words like "OFFERTA IMPERDIBILE", "ERRORI DI PREZZO".
Images sometimes are forwarded from channels or from users with Chinese names (non-latin)

This filter should help (detect and delete messages and images) in group managing

**Comment by thevyanshu** [comment]
Hey @mik3sw 
Can I contribute to this.

**Comment by mik3sw** [comment]
@thevyanshu Sure, when you have time ;)

**Comment by thevyanshu** [comment]
Tomorrow then.

**Comment by BluLupo** [comment]
Study a way to do it

**Comment by mik3sw** [comment]
Finished!
